version: '3'
services:
    nginx:
        volumes:
            - {PROJECT_NAME}-sync:/srv/app:nocopy
        environment:
            VIRTUAL_HOST: {VIRTUAL_HOST}
        networks:
            nginx-proxy: ~
            default:
                aliases:
                    - {VIRTUAL_HOST}
    app:
        build:
            args:
                ENV: dev
                USER: "{USER_ID}"
        volumes:
            - {PROJECT_NAME}-sync:/srv/app
        user: "{USER_ID}"
    db:
        volumes:
            - ./db/initdb.d:/docker-entrypoint-initdb.d
    adminer:
        image: adminer:4-standalone
        links:
            - db
        environment:
            VIRTUAL_HOST: db.{VIRTUAL_HOST}
        networks:
            - app
            - nginx-proxy
        restart: unless-stopped

networks:
    nginx-proxy:
        external:
            name: nginx-proxy

volumes:
    {PROJECT_NAME}-sync:
        external: true
